// <auto-generated />
using System;
using HarmoniQ.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarmoniQ.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260617181717_BestehendeKontenBestaetigt")]
    partial class BestehendeKontenBestaetigt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HarmoniQ.Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Land")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Webseite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bands");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.BandMitgliedschaft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BisJahr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Funktion")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InstrumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VonJahr")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PersonId");

                    b.HasIndex("BandId", "PersonId");

                    b.ToTable("BandMitgliedschaften");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.BandbeitrittAntrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeantragtVonId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntschiedenAm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InstrumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.HasIndex("BeantragtVonId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PersonId");

                    b.HasIndex("Status");

                    b.ToTable("BandbeitrittAntraege");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Bewertung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AkustischeQualitaet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnonymerCookieId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BenutzerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<int>("GesamtEindruck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kommentar")
                        .HasColumnType("TEXT");

                    b.Property<int>("Musikalitaet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Praezision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoQualitaet")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.HasIndex("VideoId", "AnonymerCookieId")
                        .IsUnique()
                        .HasFilter("[AnonymerCookieId] IS NOT NULL");

                    b.HasIndex("VideoId", "BenutzerId")
                        .IsUnique()
                        .HasFilter("[BenutzerId] IS NOT NULL");

                    b.ToTable("Bewertungen");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Instrumente");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BenutzerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BildUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Biografie")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Geburtsjahr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sichtbarkeit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId")
                        .IsUnique();

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.PersonAnspruch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Begruendung")
                        .HasColumnType("TEXT");

                    b.Property<string>("BenutzerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntschiedenAm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.HasIndex("Status");

                    b.HasIndex("PersonId", "BenutzerId", "Status");

                    b.ToTable("PersonAnsprueche");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.PersonInstrument", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("PersonInstrumente");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.PersonLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Typ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonLinks");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.PersonRolle", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rolle")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonId", "Rolle");

                    b.ToTable("PersonRollen");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Richtigstellung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Antwort")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AntwortAm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BetrifftId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BetrifftTyp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EingereichtVonId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EingereichtVonId");

                    b.HasIndex("Status");

                    b.HasIndex("BetrifftTyp", "BetrifftId");

                    b.ToTable("Richtigstellungen");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Stimme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId", "Bezeichnung")
                        .IsUnique();

                    b.ToTable("Stimmen");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Stueck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<string>("Besetzung")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Jahr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Schwierigkeitsgrad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stuecke");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.StueckBeitrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rolle")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StueckId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("StueckId", "PersonId", "Rolle")
                        .IsUnique();

                    b.ToTable("StueckBeitraege");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Anlass")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("AufnahmeDatum")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StueckId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VorgeschlagenVonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("YouTubeVideoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.HasIndex("StueckId");

                    b.HasIndex("VorgeschlagenVonId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.VideoMitwirkung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Anmerkung")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InstrumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rolle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StimmeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VorgeschlagenVonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PersonId");

                    b.HasIndex("StimmeId");

                    b.HasIndex("VideoId");

                    b.HasIndex("VorgeschlagenVonId");

                    b.ToTable("VideoMitwirkungen");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("BLOB");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.BandMitgliedschaft", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.Models.Band", "Band")
                        .WithMany("Mitgliedschaften")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HarmoniQ.Web.Data.Models.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HarmoniQ.Web.Data.Models.Person", "Person")
                        .WithMany("Bandmitgliedschaften")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Instrument");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.BandbeitrittAntrag", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.Models.Band", "Band")
                        .WithMany()
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", "BeantragtVon")
                        .WithMany()
                        .HasForeignKey("BeantragtVonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HarmoniQ.Web.Data.Models.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HarmoniQ.Web.Data.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("BeantragtVon");

                    b.Navigation("Instrument");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Bewertung", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", "Benutzer")
                        .WithMany()
                        .HasForeignKey("BenutzerId");

                    b.HasOne("HarmoniQ.Web.Data.Models.Video", "Video")
                        .WithMany("Bewertungen")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Person", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", "Benutzer")
                        .WithMany()
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.PersonAnspruch", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", "Benutzer")
                        .WithMany()
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HarmoniQ.Web.Data.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.PersonInstrument", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.Models.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HarmoniQ.Web.Data.Models.Person", "Person")
                        .WithMany("Instrumente")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.PersonLink", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.Models.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.PersonRolle", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.Models.Person", "Person")
                        .WithMany("Rollen")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Richtigstellung", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", "EingereichtVon")
                        .WithMany()
                        .HasForeignKey("EingereichtVonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EingereichtVon");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Stimme", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.Models.Instrument", "Instrument")
                        .WithMany("Stimmen")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.StueckBeitrag", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.Models.Person", "Person")
                        .WithMany("StueckBeitraege")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HarmoniQ.Web.Data.Models.Stueck", "Stueck")
                        .WithMany("Beitraege")
                        .HasForeignKey("StueckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Stueck");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Video", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.Models.Band", "Band")
                        .WithMany("Videos")
                        .HasForeignKey("BandId");

                    b.HasOne("HarmoniQ.Web.Data.Models.Stueck", "Stueck")
                        .WithMany("Videos")
                        .HasForeignKey("StueckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", "VorgeschlagenVon")
                        .WithMany()
                        .HasForeignKey("VorgeschlagenVonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Band");

                    b.Navigation("Stueck");

                    b.Navigation("VorgeschlagenVon");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.VideoMitwirkung", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.Models.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HarmoniQ.Web.Data.Models.Person", "Person")
                        .WithMany("Mitwirkungen")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HarmoniQ.Web.Data.Models.Stimme", "Stimme")
                        .WithMany()
                        .HasForeignKey("StimmeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HarmoniQ.Web.Data.Models.Video", "Video")
                        .WithMany("Mitwirkungen")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", "VorgeschlagenVon")
                        .WithMany()
                        .HasForeignKey("VorgeschlagenVonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Instrument");

                    b.Navigation("Person");

                    b.Navigation("Stimme");

                    b.Navigation("Video");

                    b.Navigation("VorgeschlagenVon");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<uint>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HarmoniQ.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Band", b =>
                {
                    b.Navigation("Mitgliedschaften");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Instrument", b =>
                {
                    b.Navigation("Stimmen");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Person", b =>
                {
                    b.Navigation("Bandmitgliedschaften");

                    b.Navigation("Instrumente");

                    b.Navigation("Links");

                    b.Navigation("Mitwirkungen");

                    b.Navigation("Rollen");

                    b.Navigation("StueckBeitraege");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Stueck", b =>
                {
                    b.Navigation("Beitraege");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("HarmoniQ.Web.Data.Models.Video", b =>
                {
                    b.Navigation("Bewertungen");

                    b.Navigation("Mitwirkungen");
                });
#pragma warning restore 612, 618
        }
    }
}
